---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleetpermit-controller
rules:
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  - placementdecisions
  - placements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fleetpermit.github.io
  resources:
  - fleetaccesspolicies
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - fleetpermit.github.io
  resources:
  - fleetaccesspolicies/status
  - toolaccessleases/status
  verbs:
  - get
  - patch
- apiGroups:
  - fleetpermit.github.io
  resources:
  - toolaccessleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - manifestworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
